# Generated by Django 3.1.3 on 2020-12-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_collectionitemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemimage',
            name='upload_date',
        ),
    ]
