# Generated by Django 3.1.3 on 2020-12-03 10:33

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_collectionitemimage_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemimage',
            name='image',
            field=models.ImageField(upload_to=community.models.content_file_name),
        ),
    ]
